### ISSUE TITLE
Reflect required changes on readme

### ISSUE THREAD

**Issue by MSNTCS** [MSNTCS/Ritamad#1]
Please change the readme file. required changes are mentioned in the file.

**Comment by r-amiri** [comment]
I cannot understand the meaning of "upload" in the instructions on README.md .
Does "upload our logo" mean uploading the black and gold picture with the big A?
And also, does "upload our sns" mean leaving the ritamad insta account link?  😶 @MSNTCS

**Comment by MSNTCS** [comment]
> I cannot understand the meaning of "upload" in the instructions on README.md .
> Does "upload our logo" mean uploading the black and gold picture with the big A?
> And also, does "upload our sns" mean leaving the ritamad insta account link? 😶 @MSNTCS

Look at the foundry repo for example, you will see some art effect in front of the Foundry in the first line.
![Screen Shot 2020-07-21 at 11 43 28 AM](https://user-images.githubusercontent.com/50092326/88006958-d717d000-cb47-11ea-8df8-9b3599ff9aba.png)
 I want the same thing for our social contact points. for the first one you can upload your youtube logo as a picture on readme.

**Comment by r-amiri** [comment]
Thank you for this question. It wasn't about editing after all; with help from a 30-minute video on Youtube and lots of webpages, I did indeed succeed to clear all the confusion I had from yesterday to this date. I will practice the flow a bit more to get a good grasp of everything.

**Comment by MSNTCS** [comment]
> Thank you for this question. It wasn't about editing after all; with help from a 30-minute video on Youtube and lots of webpages, I did indeed succeed to clear all the confusion I had from yesterday to this date. I will practice the flow a bit more to get a good grasp of everything.

Goof job. Good luck. You are learning faster than me 👍
