### ISSUE TITLE
Learn cherry-pick

### ISSUE THREAD

**Issue by MSNTCS** [MSNTCS/Ritamad#12]
Learn to add a special commitment to a  different branch.

**Comment by r-amiri** [comment]
I am afraid I do not understand the issue... :(

Is it supposed to mean adding an arbitrary commit to a specific branch?

Like in log, if I have
Commit1 Hash1
Commit2 Hash2
Commit3 Hash3
Commit4 Hash4
I decide to add Commit2 to Branch2
and only that commit? (Not the ones following it)
?
