### ISSUE TITLE
Add Apache License 2.0

### ISSUE THREAD

**Issue by MSNTCS** [MSNTCS/Ritamad#2]
The current Licence is MIT. Please add another license called Apache License 2.0.

**Comment by r-amiri** [comment]
One license can point to each part of a project, and merging licenses is possible manually while it will change the visible structure in the Github website to a normal text file. I just decided to change the license to Apache altogether while adding a text file and copying the contents of the Apache license required us to determine which parts of our great project are under Apache and which under MIT. :)
